### PR TITLE
Services and clients

### PR DESCRIPTION
**Pull request by FelixPe**
An initial implementation of services and clients as a basis for discussion.

### CODE REVIEW

**Comment by takasehideki** [comment]
Hi, @FelixPe thank you so much for your contribution!!
I have said it many times, but I want to say it again and again because it is important :D

I had a chance to discuss with @pojiro about how to proceed with this new awesome feature you are working on.
Ideally, when adding a new feature, it would be nice to be able to review the detailed internal implementation that makes it possible, but we can't always take the time to do so. As a reasonable compromise, we would like to proceed once we have agreed on an external API specification.
Therefore, we want to suggest a way of proceeding as below. We hope you agree with this.

As for your proposals regarding new features, we would like to ask you to indicate the following three points:

1. specification of new APIs 
2. simple example to use these APIs
3. reasonable test code of new features

We would like to merge your contributions if we can agree on these points.

As for this PR, the test code is already sufficient, but I feel that it lacks a description of the new APIs and examples of how to use them. When you are ready, please change this PR to "ready for review", and could you please indicate these? (in the comment field is acceptable)

In addition, I think that the addition of new features, such as service in this PR and graph introspection in #306, should be released with the next new minor number (v0.11). On the other hand, we found that some improvements need to be resolved in the current v0.10, as in #317.
For this reason, I have created a branch `v0.11.0-dev` from the commit you started working on. Could you please change the base branch for this PR? From now on we may make some additions to `main` for `v0.10.x`, but your work does not need to merge these.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by FelixPe** [comment]
The approach is not compatible to jazzy, so I need to change it.

**Comment by FelixPe** [comment]
> The approach is not compatible to jazzy, so I need to change it.

Instead of using the request and response msgs that, where available before jazzy, it's now working on the srv file to extract request and response msg type.

**Comment by FelixPe** [comment]
Let's define a nice api for services/clients first - right now it's very prototypically implemented. I started a discussion here: https://github.com/rclex/rclex/issues/336#issue-2410552700

**Pull request closed without merging**
