### PR TITLE
Enhance msgs

### LINKED ISSUE #311: message generation for type std_msgs/msg/Empty failing
The message parser fails for the type `std_msgs/msg/Empty`.

### LINKED ISSUE #312: message generation for action_msgs/msg/GoalInfo is failing
```
config :rclex,
  ros2_message_types: [
    "action_msgs/msg/GoalInfo"
  ]
```

The array type of the uuid is giving the generator headaches as it's not a sequence:
`message_p->goal_id.uuid = goal_id_uuid;`

```
# Goal ID
unique_identifier_msgs/UUID goal_id

# Time when the goal was accepted
builtin_interfaces/Time stamp
```

```
# A universally unique identifier (UUID).
#
#  http://en.wikipedia.org/wiki/Universally_unique_identifier
#  http://tools.ietf.org/html/rfc4122.html

uint8[16] uuid
```

The static array type translates to DDS type `T[N]`
as in
unique_identifier_msgs/unique_identifier_msgs/msg/detail/uuid__struct.h
```
typedef struct unique_identifier_msgs__msg__UUID
{
  uint8_t uuid[16];
} unique_identifier_msgs__msg__UUID;
```

Would be function get_array_type(type) for parsing msgs be a good starting point to destinguish between the different types of arrays?:
```
    {:ok, acc, _rest, _context, _line, _column} = TypeParser.parse(type)
    case acc do
      [type, "[", size, "]"] -> {type, :static_array, size}
      [type, "[]"] -> {type, :unbounded_dynamic_array, 0}
    end
 ```

### PR DESCRIPTION
**Pull request by pojiro**
This PR's purpose are followings

- [x] #316 by a different way, see 60f50f2bd71f5592bdfdbfe0b1a0c35b3fe0d05c
- [x] fix #311 see 70d20ebbd4e4969115958d808d1777768760e4be
- [x] fix #312 see 67c8963f08cbc4695ef3aa16190d24ac0ecd0204

### CODE REVIEW

**Comment by FelixPe** [comment]
Hi @pojiro, 

thank you for this enhancement of msgs. I know this PR is just an intermediate state, but I already like it - especially the binaries. It's sad that is is not possible to distinguish in a message type between an arrays of uint8 and BLOBs.
Regarding the empty message type, it is hard to find a nice solution to this. I started a similar approach, which you can find here: 
https://github.com/FelixPe/rclex/commit/8591f664295a635703bda6aa4828708bdc3d6cd4
The disadvantege of my approach is, that it exposes the (not so nice) internals of the c/idl code, which don't allow to have empty structs - your PR hides these internals much better from the user.
On the other hand the advantage is, that is works on any message type without fields. For pub/sub empty messages are not so common, but for the messages of service requests and responses is was giving me headaches. (e.g.: std_srvs/srv/Trigger_Request.msg)

**Comment by pojiro** [comment]
@FelixPe Thanks to quick your review.

> It's sad that is is not possible to distinguish in a message type between an arrays of uint8 and BLOBs.

Do you think is that helpful to user that we can distinguish them? I just think it's ok to user 8 bit array can be always binary. Because user can know about the type, they can convert it very easiley to charlist. What do you think about this?

I didn't know there are like `e.g.: std_srvs/srv/Trigger_Request.msg` which dones't have any fields. Thank you.
I saw your commit. I would like to think about more better handling like mixex you way and my way.

**Comment by FelixPe** [comment]
Regarding the right choice between binary and lists it might be good to push this decision to the user as mentioned by @takasehideki in https://github.com/rclex/rclex/pull/316#issuecomment-2067946877
If it's implemented in this non-configurable way, using binary for fixed-sized size arrays of uint8 might be less confusing, than using different types depending on the array type (dynamic/fixed size). Converting from binary to list is very cheap for uint8 and the binaries allow fast binary pattern matching.

**Comment by pojiro** [comment]
@FelixPe @takasehideki 

I think it's difficult to handle uint8 array with option. Because if we use two message types, each of them uses same uint8 array in their dependency. like 

```
config :rclex,
  ros2_message_types: [
    {"A", :uint8_array_as_binary},
    "B",
  ]
# A and B uses C, C has uint8[]
```

This cannot be worked. Because `gen.msgs` generates only one C message type source.
If you have any ideas to make this possible, please let me know.

---

If we choose treating uint8 array as binary, I think it makes sense as @FelixPe said, https://github.com/rclex/rclex/pull/316#issuecomment-2059007090.

We can also apply this for static array too, like `unique_identifier_msgs/msg/UUID.msg` which is represented by `uint8[16] uuid`.

Ecto.UUID's raw representations is also binary, ref. https://hexdocs.pm/ecto/Ecto.UUID.html#t:raw/0

We think about only one thing for this way is this will make breaking change. 

I'd like to hear both of your thoughts .

**Comment by takasehideki** [comment]
OK, I've totally agreed with your idea, treat uint8 as binary ❤️ > @pojiro @FelixPe 

One of my slight concerns is that It may cause performance degradation as far as DDS communication by giving special treatment to Elixir's situation. However, I can't immediately think of any mechanism or reason why that could happen, and I doubt it will ever occur.

**Comment by FelixPe** [comment]
Sorry, for the late response. The inconsistencies that would be introduced by a configurable approach are a really convincing reason to go the other way. And I hope the user also benefits from this stringent approach, where uint8[] is always a binary.
Regarding performance impact, I expect some improvement on the elixir side.

**Comment by FelixPe** [comment]
@pojiro I found one minor issue, but I need to double check, for arrays of strings like in `sensor_msgs/msg/JointState` rcl expects in its function calls String instead of string. Giving you the message:
`warning: implicit declaration of function ‘rosidl_runtime_c__string__Sequence__init’; did you mean ‘rosidl_runtime_c__String__Sequence__init`
I tried to solve this by looking for string type during sequence type generation (see https://github.com/rclex/rclex/commit/bfa9d115bd66c74851e01368515dad6422e3744f#diff-9ab5d2fe80333211524095cd91c8e3b30e0df45ecc6e93d146ac9086db7f55b8R182-R185)

**Comment by pojiro** [comment]
@FelixPe cc @takasehideki 

I'm sorry for my slow hand! Thanks for your reporting I fixed it.
I grepped all rosidl_runtime_c__types. I hope this will not happen again.

```sh
rg --no-filename --no-line-number "rosidl_runtime_c__[^_]+__Sequence " /opt/ros/foxy/ | sed -E 's/.+(rosidl_runtime_c__[^_]+__Sequence).+/\1/' | sort | uniq
rosidl_runtime_c__String__Sequence
rosidl_runtime_c__String__Sequence *
rosidl_runtime_c__U16String__Sequence
rosidl_runtime_c__U16String__Sequence *
rosidl_runtime_c__boolean__Sequence
rosidl_runtime_c__double__Sequence
rosidl_runtime_c__float__Sequence
rosidl_runtime_c__int16__Sequence
rosidl_runtime_c__int32__Sequence
rosidl_runtime_c__int64__Sequence
rosidl_runtime_c__int8__Sequence
rosidl_runtime_c__octet__Sequence
rosidl_runtime_c__uint16__Sequence
rosidl_runtime_c__uint32__Sequence
rosidl_runtime_c__uint64__Sequence
rosidl_runtime_c__uint8__Sequence
```

**Comment by FelixPe** [comment]
Looks like the to_down_snake needs a minor change
std_msgs/msg/UInt32.msg becomes u_int32.h
but tf2_msgs/msg/TF2Error.msg doesn't tf2_error.h but t_f2_error.h

It done in two steps in rosidl:

https://github.com/ros2/rosidl/blob/481c9437ab3dbf92807f8b2fb0b0bad5ba22d4bf/rosidl_cmake/cmake/string_camel_case_to_lower_case_underscore.cmake#L16

**Comment by FelixPe** [comment]
Thanks you for your awesome work. Even bounded arrays are supported. 👍🏻

**Comment by pojiro** [comment]
@FelixPe Nice catch!

I'd like to add your name as co-author, so I wanna know which email address do you want to add? gmail or other?

**Comment by FelixPe** [comment]
> @FelixPe Nice catch!
> 
> I'd like to add your name as co-author for the commit of `to_down_snake` fix, so I wanna know which email address do you want to add? gmail or other? Now i added with gmail one. If you want to change it, let me know i will fix.

Thank you, gmail is fine :)

**Review by takasehideki — APPROVED** [review]
@pojiro @FelixPe Thank you so much for your great effort on this PR!!
I decided to merge this to upstream, and make a new release along with merging dependabot updates 🙌 
Since this improvement includes the breaking change to handle `uint8[]` as binary, `v0.11.0` is good as the new release.

**Pull request merged**
