### PR TITLE
create GHA to publish to Hex when tags released

### PR DESCRIPTION
**Pull request by takasehideki**
We will merge this PR just before publishing the next new release.

### CODE REVIEW

**Comment by takasehideki** [comment]
@mnishiguchi taught us a cool solution!
https://github.com/elixir-sensors/sgp40/commit/f172bdc4d5e02ad6812b0252314fb8fab017e83a

**Comment by takasehideki** [comment]
Woops!! `mix compile` failed due to miss the Hex.
https://github.com/rclex/rclex/runs/3149862718?check_suite_focus=true

```
1s
Run source /opt/ros/${ROS_DISTRO}/setup.bash
  source /opt/ros/${ROS_DISTRO}/setup.bash
  mix deps.get
  mix compile
  shell: bash --noprofile --norc -e -o pipefail {0}
Could not find Hex, which is needed to build dependency :credo
** (Mix) Could not find an SCM for dependency :credo from Rclex.MixProject
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] 
Error: Process completed with exit code 1.
```

**Comment by takasehideki** [comment]
Woooopppss!! `HEX_API_KEY: ${{ secrets.HEX_API_KEY }}` was missing :D
https://github.com/rclex/rclex/runs/3149895568?check_suite_focus=true

**Comment by mnishiguchi** [comment]
🎉

**Pull request merged**
