### PR TITLE
add qos options for publisher and subscription, use enif_allocator

### PR DESCRIPTION
**Pull request by FelixPe**
- add options for qos on publisher and subscription
- use enif allocator

### CODE REVIEW

**Comment by takasehideki** [comment]
Hi @FelixPe thank you so much for sharing your contribution with us! I think QoS setting is very important not only for ROS/DDS communication but also for our Rclex library.

The first question is we wanna know your motivation for wanting to create this PR / add QoS feature to Rclex. Any use case of sample application code for using QoS would be appreciated. Or, it would be helpful to add a test code as well.

And more, please let me know if there is also a reason why you sent this PR to `v0.10.0-dev`, not `main`.
Actually, `v0.10.0-dev` is still under development and we are considering major changes to the API specification. If you want to use the QoS features ASAP, we are happy to merge your contribution to `main` and release a new version `v0.9.3`.

**Comment by FelixPe** [comment]
Hi @takasehideki, thank you and your team for bringing ROS 2 to elixir. To me it is a perfect fit for robotics.
My personal motivation was, to be able to publish to the logging topic /rosout, the publisher is required to be configured with compatible qos parameters. Messages by incompatible publishers are not received. Logging is not an ideal example for qos, as this topic is covered by rcl it self quite well. I'll prepare an example on that as part of the tests.
To be honest the v0.10.0 branch made me curious and looked like the right place to evaluate new additions, so I implement based on it. I will prepare the PR based on main and close this PR for now.

**Comment by takasehideki** [comment]
Thank you so much for your reply!
I can understand your motivation. But I think that logging and Rqt no longer work with the default BestEffort setting is more the fault of the ROS 2 update, though,,, Anyway, I agree with your opinion that QoS functionality should be added to this library.

And, I'd like to retract my earlier comment.
>  If you want to use the QoS features ASAP, we are happy to merge your contribution to main and release a new version v0.9.3.

In v0.10.0, the implementation within the library has already been changed to a near redesign level from v0.9.2. IOW, reimplementing this PR for the current `main` would likely be a waste of your time and contribution. 
As noted above, the remaining work to release v0.10.0 will include the redesign and its implementation of the API specification. 
So my suggestion is that, I'm not sure how long it will take yet, butcould you wait a while for our work?
If you can, once the API has been redesigned and a new version can be released, we would like to review this PR work of yours again.

**Comment by FelixPe** [comment]
Thank you, that is totally fine from my side. I would be happy to support as a tester for the redesigned API. As soon as v0.10.0 get's more stable, I'll rebase the PR to fit the newest interface.

**Pull request closed without merging**
